### PR TITLE
Day Of Week support

### PR DESCRIPTION
**Pull request by KazukiOhno**
I modified the source program for 
1. changing the character of day of the week by seudo alphabet,
2. adding a smooth function to alarm,
3. changing back to the original display sequence as showing temperature, date and weekday automatically,
4. adapting leap year by using a function of calendar IC DS1302 by setting year.

### CODE REVIEW

**Comment by zerog2k** [comment]
Hi KO,
first of all thanks for contributing significant features! Sorry for the delay, I just got back from some holiday travel.

A few notes:
1. Yes, please do ensure all comments are in English and source files are all ascii. If you would like to include a separate JP "readme" file with notes, etc, that would be good.
2. Please remove any "added by..." comments; should keep comments pure and simple. Github will track and attribute all of your commits and additions automatically, e.g. `git blame`.
3. I think the feature you are adding is called commonly called "snooze". Please update references in the code to this.
4. It's not so obvious to casual reader how you are indexing into the alphabet characters in `ledtable` for displaying DOW. Maybe you can improve this, or put some comment in the code on what is happening.
5. Is the behavior of cycling through temperature, date, etc, a run-time configurable option? If not, can we make this a compile-time option, i.e. some people may not like that (or maybe want a different cycle frequency, etc).

**Comment by zerog2k** [comment]
Hi KO,
first of all thanks for contributing significant features! Sorry for the delay, I just got back from some holiday travel.

A few notes:
1. Yes, please do ensure all comments are in English and source files are all ascii. If you would like to include a separate JP "readme" file with notes, etc, that would be good.
2. Please remove any "added by..." comments; should keep comments pure and simple. Github will track and attribute all of your commits and additions automatically, e.g. `git blame`.
3. I think the feature you are adding is called commonly called "snooze". Please update references in the code to this.
4. It's not so obvious to casual reader how you are indexing into the alphabet characters in `ledtable` for displaying DOW. Maybe you can improve this, or put some comment in the code on what is happening.
5. Is the behavior of cycling through temperature, date, etc, a run-time configurable option? If not, can we make this a compile-time option, i.e. some people may not like that (or maybe want a different cycle frequency, etc).

**Comment by KazukiOhno** [comment]
Hello, Jens,

I updated my files to following your comments. Please take a check them.
I have one comment.
For #5 of your comment, I put it with SHOW_TEMP_DATE_WEEKDAY word. And I modified CFLAGS in Makefile. I'm not sure this is right way or not. And I don't know where should I write this option. 
Please teach me.

**Comment by KazukiOhno** [comment]
Thank you for your support and merging my code.
This is my very pleasure.

Thanks,

**Comment by KazukiOhno** [comment]
Thank you for your support and merging my code.
This is my very pleasure.

Thanks,

**Pull request merged**
